 <%@ page contentType="text/html; charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
   <p class="w-100 float-left my-3" style="text-align: center;"><span style="font-size: large;"><strong>PHẦN II. QUY TRÌNH GIAO DỊCH</strong></span></p>
   <p><span id="docs-internal-guid-50932c38-7fff-3af3-c968-ffd847f1ca94" style="font-size: medium;"><strong>1.&nbsp;<strong>Dành cho người mua hàng tại Website:</strong></strong></span></p>
   <p><span id="docs-internal-guid-50932c38-7fff-3af3-c968-ffd847f1ca94" style="font-size: medium;"><strong>Bước 1:</strong> Quý khách tìm sản phẩm cần mua. đọc và đồng ý với các quy định tại “Quy chế hoạt động website cung cấp dịch vụ TMĐT Cellphones.com.vn”</span></p>
   <p><span style="font-size: medium;"><strong>Bước 2:</strong> Xem giá và thông tin chi tiết sản phẩm đó, nếu đồng ý muốn mua hàng, Quý khách tùy theo yêu cầu của mình và từng mặt hàng mua để bấm vào một trong 3 nút: “Mua ngay (giao hàng tận nơi hoặc lấy tại cửa hàng” hoặc “Trả góp (Xét duyệt qua điện thoại)”, “Trả góp qua thẻ (Visa, Master, JCB)”</span></p>
   <p><span style="font-size: medium;"><strong>Bước 3:</strong> Quý khách nhập thông tin mua hàng theo chỉ dẫn tại từng mục mua hàng mà Quý khách đã lựa chon tại phần trên.</span></p>
   <p><span style="font-size: medium;"><strong>Nếu Quý khách có mã khuyến mại có thể nhập trực tiếp vào form đặt mua</strong></span></p>
   <p><span style="font-size: medium;"><strong>Bước 4:</strong> Sau khi nhận đơn hàng của người mua, Cellphones.com.vn sẽ liên lạc với khách hàng qua thông tin số điện quý khách hàng cung cấp bằng tổng đài&nbsp;<em><strong>1800.2063</strong></em> để xác thực thông tin đơn hàng.</span></p>
   <p><span style="font-size: medium;"><strong>Bước 5:</strong>&nbsp;Cellphones.com.vn giao hàng đến tận nhà cho khách hàng hoặc khách hàng đến trực tiếp các cửa hàng Cellphones toàn quốc để nhận hàng.</span></p>
   <p><span id="docs-internal-guid-50932c38-7fff-3af3-c968-ffd847f1ca94" style="font-size: medium;"><strong><strong>2. Quy trình giao nhận vận chuyển</strong></strong></span></p>
   <p><span style="font-size: medium;">Cellphones.com.vn thực hiện giao hàng miễn phí trên toàn quốc. Khi nhận đơn hàng từ người mua và sau khi đã xác thông tin mua hàng qua điện thoại, Cellphones.com.vn sẽ tiến hành giao hàng theo yêu cầu của quý khách hàng</span></p>
   <p><span style="font-size: medium;">Với các giao dịch từ 10 triệu đồng trở lên, Quý Khách hàng vui lòng cung cấp <strong>THẺ VẬT LÝ (THẺ CỨNG)</strong> và <strong>CCCD BẢN GỐC</strong> của <strong>ĐÚNG CHỦ THẺ</strong> để CellphoneS đối chiếu trước khi tiến hành giao hàng nhằm hạn chế các trường hợp gian lận. Trường hợp không phải <strong>ĐÚNG CHỦ THẺ</strong> nhận hàng hoặc nhận thấy giao dịch có vấn đề, CellphoneS có quyền quyết định huỷ giao dịch &amp; hoàn tiền cho <strong>CHỦ THẺ</strong>, thời gian hoàn tiền từ 7 - 14 ngày (không tính T7&amp;CN).</span></p>
